Adjust docker settings with project
NicolasPineau/modulo-back pull request #1
Opened 2022-03-31 11:43 UTC by Fuzzy2319

Change database to mysql
Remove caddy to use nginx
Add .env file
Fix fixtures
Adjust migration
Update dependencies
Use npm instead of yarn

2022-04-04 21:37 UTC, NicolasPineau commented on .dockerignore
> -.env.local
Celui-là tu peux le laisser ;)

2022-04-04 21:44 UTC, NicolasPineau commented on src/DataFixtures/UserFixture.php
> +            $email = $faker->email();
Je préfère conserver une correspondance entre les noms/prénoms et l'email, mais peut-être as-tu fait cette modif pour corriger un bug que tu as rencontré ?

2022-04-04 21:44 UTC, NicolasPineau commented on composer.json
> +        "fakerphp/faker": "^1.5",
:+1:

2022-04-04 21:46 UTC, NicolasPineau commented on Makefile
> -# Executables (local)
Il ne faut pas supprimert ce fichier, il ne vous sera peut-être pas indispensable mais moi je vais en avoir besoin :)
Je ferai du ménage dedans quand j'aurais le temps

2022-04-04 21:52 UTC, NicolasPineau requested changes
Merci pour le nettoyage ;)
J'ai mis quelques commentaires.

2022-04-04 21:54 UTC, NicolasPineau commented on src/DataFixtures/UserFixture.php
> +            $email = $faker->email();
Un doublon ?

2022-04-05 06:35 UTC, Fuzzy2319 commented on src/DataFixtures/UserFixture.php
> +            $email = $faker->email();
quand j'ai load les fixtures j'ai eu un doublon donc j'ai changé pour plus avoir de doublon

2022-04-05 06:36 UTC, Fuzzy2319 commented on .dockerignore
> -.env.local
ok

2022-04-05 06:37 UTC, Fuzzy2319 commented on Makefile
> -# Executables (local)
je le remet

2022-04-05 07:11 UTC, closed without merging